#cloud-config 
package_upgrade: true
packages:
  - open-vm-tools
users:
  - default
  - name: shturval
    ssh-authorized-keys:
      - "{{ ssh_key }}"
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: [sudo,docker]
    shell: /bin/bash
ssh_pwauth: True
chpasswd:
  list:
    - shturval:password
